{{- range $i, $job := $.Values.jobs }}
{{- if not $job.filter.namespaces.all }}
{{- range $j, $namespace := $job.filter.namespaces.specific }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "krar.roleName" $ }}-{{ $job.name}}
  namespace: {{ $namespace }}
  labels:
    {{- include "krar.labels" $ | nindent 4 }}
  {{- with $.Values.roleAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [ "apps" ]
    resources:
      {{- toYaml (append $job.filter.resources "replicasets") | nindent 6 }}
    verbs: ["get", "patch", "list"]
  - apiGroups: [ "" ]
    resources:
      - pods
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources:
      - events
    verbs: [ "create" ]

---
{{- end }}
{{- end }}
{{- end }}