{{- range $i, $job := $.Values.jobs }}
{{- if not $job.filter.namespaces.all }}
{{- range $j, $namespace := $job.filter.namespaces.specific }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "krar.roleName" $ }}-{{ $job.name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "krar.labels" $ | nindent 4 }}
  {{- with $.Values.roleBindingAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: {{ include "krar.roleName" $ }}-{{ $job.name }}
subjects:
  - kind: "ServiceAccount"
    name: {{ include "krar.serviceAccountName" $ }}-{{ $job.name }}
    namespace: {{ $.Release.Namespace }}

---
{{- end }}
{{- end }}
{{- end }}
